### ISSUE TITLE
Refactor Button Scripts

### ISSUE THREAD

**Issue by kylemas** [ubcemergingmedialab/Jupyter3D-Unity#40]
Currently there are 3 separate scripts for the buttons: play, pause, reset, back.

Refactor this into one file that can call different functions for each to lessen overall unity project size.

**Comment by willjvan** [comment]
I just added a button to toggle the controller image description that Sandy is working on so we should probably include this button's script in the refactoring!

**Comment by kylemas** [comment]
Closed by #41
